"""Release state compatibility exports.

The current SQLite implementation still lives in ``builder.src.release_state``.
This module provides the target import path for the refactoring.
"""

from __future__ import annotations

from builder.src.release_state import (  # noqa: F401
    CONTOURS,
    JOB_STATUSES,
    REQUEST_STATUSES,
    ContourState,
    ExternalRequest,
    JobRecord,
    all_contour_states,
    connect_state_db,
    create_external_request,
    create_job,
    default_state_db_path,
    ensure_schema,
    get_external_request,
    get_contour_state,
    get_job,
    list_build_attempts,
    list_deployment_attempts,
    list_external_requests,
    list_jobs,
    list_releases,
    mark_job_finished,
    mark_job_started,
    record_attempt,
    record_build_attempt_finished,
    record_build_attempt_started,
    record_release,
    update_external_request_status,
    upsert_contour_state,
    utc_now,
    validate_contour,
    validate_status,
)

__all__ = [
    "CONTOURS",
    "JOB_STATUSES",
    "REQUEST_STATUSES",
    "ContourState",
    "ExternalRequest",
    "JobRecord",
    "all_contour_states",
    "connect_state_db",
    "create_external_request",
    "create_job",
    "default_state_db_path",
    "ensure_schema",
    "get_external_request",
    "get_contour_state",
    "get_job",
    "list_build_attempts",
    "list_deployment_attempts",
    "list_external_requests",
    "list_jobs",
    "list_releases",
    "mark_job_finished",
    "mark_job_started",
    "record_attempt",
    "record_build_attempt_finished",
    "record_build_attempt_started",
    "record_release",
    "update_external_request_status",
    "upsert_contour_state",
    "utc_now",
    "validate_contour",
    "validate_status",
]
